weights: 'src/weights/yolov9-c.pt'
source: 'data/images' #provide path to images for prediction.
data: 'data/coco128.yaml' #provide path to data.yaml
imgsz: [640]
conf_thres: 0.25
iou_thres: 0.45
max_det: 1000
device: ''
view_img: false
save_txt: false
save_conf: false
save_crop: false
nosave: false
classes: null
agnostic_nms: false
augment: false
visualize: false
update: false
project: 'runs/detect'
name: 'exp'
exist_ok: false
line_thickness: 3
hide_labels: false
hide_conf: false
half: false
dnn: false
vid_stride: 1