data: '/content/DeepFashion2-1/data.yaml'
weights: '/content/Multi-Head-Yolov9/src/weights/gelan-c-seg.pt'
batch_size: 8
imgsz: 640
conf_thres: 0.001
iou_thres: 0.6
max_det: 300
task: 'val'
device: ''
workers: 8
single_cls: false
augment: false
verbose: false
save_txt: false
save_hybrid: false
save_conf: false
save_json: false
project: 'runs/val-seg'
name: 'exp'
exist_ok: false
half: false
dnn: false